# Generated by Django 3.2.12 on 2022-03-01 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0039_add_new_unique_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_live_from', models.DateTimeField(null=True)),
                ('from_feature_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_change_requests', to='features.featurestate')),
                ('to_feature_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_change_requests', to='features.featurestate')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequestApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.changerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
